
export const T = {
  bg:       '#FFFFFF',
  surface:  '#F8FAFC',
  border:   '#E2E8F0',
  borderHi: '#CBD5E1',
  text:     '#0F172A',
  muted:    '#64748B',
  faint:    '#F1F5F9',
  amber:    '#D97706',
  red:      '#DC2626',
  green:    '#059669',
  blue:     '#2563EB',
  purple:   '#7C3AED',
  white:    '#FFFFFF',
}

export const MATURITY = [
  { level: 1, tag: 'Analogue HR',      color: '#E8455A', reduction: '35–45%'  },
  { level: 2, tag: 'Ad-hoc AI',        color: '#F5A623', reduction: '25–35%'  },
  { level: 3, tag: 'Structured Pilot', color: '#EAD64B', reduction: '15–25%'  },
  { level: 4, tag: 'Integrated AI',    color: '#2DD4A0', reduction: '5–15%'   },
  { level: 5, tag: 'AI-Native HR',     color: '#4F8EF7', reduction: 'Advisory'},
];

export const AREAS = [
  {
    id: 'ta', num: '01', label: 'Talent Acquisition', color: '#6366F1', impactWeight: 0.90, effortSaving: 'Up to 60%',
    questions: [
      {
        id: 'ta1', type: 'maturity', text: 'How are CVs and job applications currently screened?',
        options: [
          { label: 'Manually – a recruiter reads every application', value: 0 },
          { label: 'Basic ATS keyword filters, reviewed by a recruiter', value: 1 },
          { label: 'Structured scoring rubric, applied manually', value: 2 },
          { label: 'AI-assisted ranking with human review at shortlist', value: 4 },
        ],
      },
      {
        id: 'ta2', type: 'maturity', text: 'How are job descriptions created for new or replacement roles?',
        options: [
          { label: 'Copy-pasted from old JDs with minimal edits', value: 0 },
          { label: 'Written from scratch by a recruiter or HRBP each time', value: 1 },
          { label: 'Standard template, manually reviewed against market benchmarks', value: 2 },
          { label: 'AI-drafted and auto-benchmarked against market language', value: 4 },
        ],
      },
      {
        id: 'ta3', type: 'maturity', text: 'How is candidate communication managed during the hiring process?',
        options: [
          { label: 'All emails sent manually by the recruiter', value: 0 },
          { label: 'Templated emails exist but are sent and tracked manually', value: 1 },
          { label: 'ATS handles some automated updates; scheduling is still manual', value: 2 },
          { label: 'Fully automated – scheduling, updates, and rejections handled by system', value: 4 },
        ],
      },
      {
        id: 'ta4', type: 'maturity', text: 'Is cost-per-hire and time-to-hire tracked and benchmarked against sector data?',
        options: [
          { label: 'Not tracked at all', value: 0 },
          { label: 'Tracked informally or occasionally', value: 1 },
          { label: 'Tracked consistently but not benchmarked externally', value: 2 },
          { label: 'Tracked, benchmarked against sector data, reviewed at board level', value: 4 },
        ],
      },
      {
        id: 'ta5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When a hiring manager raises a new vacancy, how long before candidates are actively being interviewed?',
        options: [
          { label: 'More than 6 weeks – a persistent and recognised problem', value: 0 },
          { label: '4–6 weeks – slow but considered normal', value: 1 },
          { label: '2–4 weeks – acceptable but with room to improve', value: 2 },
          { label: 'Under 2 weeks – a fast, efficient process', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'ob', num: '02', label: 'Onboarding', color: '#8B5CF6', impactWeight: 0.85, effortSaving: 'Up to 70%',
    questions: [
      {
        id: 'ob1', type: 'maturity', text: 'How are employment contracts and offer letters generated?',
        options: [
          { label: 'Manually drafted from a Word template each time', value: 0 },
          { label: 'Template-based but require manual data entry and checking', value: 1 },
          { label: 'System-generated but reviewed and sent manually by HR', value: 2 },
          { label: 'Auto-generated from HRIS data and e-signed with no manual steps', value: 4 },
        ],
      },
      {
        id: 'ob2', type: 'maturity', text: 'How consistent is the onboarding experience across different managers and departments?',
        options: [
          { label: 'Entirely inconsistent – depends wholly on the line manager', value: 0 },
          { label: 'A checklist exists but is irregularly followed', value: 1 },
          { label: 'A structured programme exists but is the same for every role', value: 2 },
          { label: 'Personalised, role-specific programme with tracked completion', value: 4 },
        ],
      },
      {
        id: 'ob3', type: 'maturity', text: 'How do new hires get answers to questions in their first 30 days?',
        options: [
          { label: 'They email or call HR directly – handled individually each time', value: 0 },
          { label: 'A static intranet folder – hard to navigate, often out of date', value: 1 },
          { label: 'A basic FAQ portal – covers common questions but not all', value: 2 },
          { label: 'An AI assistant that answers questions instantly, 24/7', value: 4 },
        ],
      },
      {
        id: 'ob4', type: 'maturity', text: 'How is IT access, equipment, and system provisioning handled for new starters?',
        options: [
          { label: 'Manually requested by HR or manager – frequently delayed', value: 0 },
          { label: 'A request is raised but each team acts independently', value: 1 },
          { label: 'A checklist is followed but cross-team coordination is manual', value: 2 },
          { label: 'Automatically triggered on hire confirmation across all teams', value: 4 },
        ],
      },
      {
        id: 'ob5', type: 'bottleneck', text: 'BOTTLENECK CHECK – What is your approximate 90-day new hire attrition rate?',
        options: [
          { label: 'Above 15% – a significant, known problem', value: 0 },
          { label: '10–15% – higher than we\'d like but not formally addressed', value: 1 },
          { label: '5–10% – monitored but no systematic onboarding intervention', value: 2 },
          { label: 'Below 5% – tracked carefully with proactive onboarding in place', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'ld', num: '03', label: 'L&D', color: '#0EA5E9', impactWeight: 0.70, effortSaving: 'Up to 55%',
    questions: [
      {
        id: 'ld1', type: 'maturity', text: 'How is most learning and development content created?',
        options: [
          { label: 'Bought from external providers or agencies', value: 0 },
          { label: 'Built in-house using PowerPoint or a basic authoring tool', value: 1 },
          { label: 'Mix of bought and built, with some internal curation', value: 2 },
          { label: 'AI-assisted authoring – content generated from internal knowledge', value: 4 },
        ],
      },
      {
        id: 'ld2', type: 'maturity', text: 'How personalised are learning pathways for individual employees?',
        options: [
          { label: 'One-size-fits-all catalogue – everyone sees the same content', value: 0 },
          { label: 'Role-based curricula exist for some functions, not all', value: 1 },
          { label: 'Manager-recommended learning – no system-driven personalisation', value: 2 },
          { label: 'AI-driven recommendations based on role, skills gaps, and career goals', value: 4 },
        ],
      },
      {
        id: 'ld3', type: 'maturity', text: 'How is learning effectiveness measured?',
        options: [
          { label: 'It isn\'t – completion rates are the only metric used', value: 0 },
          { label: 'Post-course satisfaction surveys only', value: 1 },
          { label: 'Line manager feedback gathered informally after key programmes', value: 2 },
          { label: 'Learning outcomes linked to performance data and business KPIs', value: 4 },
        ],
      },
      {
        id: 'ld4', type: 'maturity', text: 'How are skills gaps across the organisation identified and tracked?',
        options: [
          { label: 'They aren\'t – it\'s reactive when a gap becomes a problem', value: 0 },
          { label: 'Annual performance reviews surface some gaps, informally', value: 1 },
          { label: 'Skills assessments exist for some roles but aren\'t consolidated', value: 2 },
          { label: 'A live skills inventory maintained and linked to L&D and hiring plans', value: 4 },
        ],
      },
      {
        id: 'ld5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When a business priority emerges requiring new skills, how long before relevant training is available to staff?',
        options: [
          { label: 'Months – content commissioning and build takes a long time', value: 0 },
          { label: '4–8 weeks – faster if bought in, but still slow', value: 1 },
          { label: '2–4 weeks – some agility exists for priority topics', value: 2 },
          { label: 'Days – AI-assisted authoring means content turned around rapidly', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'pm', num: '04', label: 'Performance Management', color: '#10B981', impactWeight: 0.85, effortSaving: 'Up to 65%',
    questions: [
      {
        id: 'pm1', type: 'maturity', text: 'How are performance reviews currently written?',
        options: [
          { label: 'Managers write from scratch with no structured data inputs', value: 0 },
          { label: 'Managers complete a form but guidance and inputs are minimal', value: 1 },
          { label: 'Structured form with ratings but free-form narrative by managers', value: 2 },
          { label: 'AI drafts the narrative from performance data – managers approve', value: 4 },
        ],
      },
      {
        id: 'pm2', type: 'maturity', text: 'How long does the annual performance review cycle take end-to-end?',
        options: [
          { label: 'More than 8 weeks – a significant drag on management time', value: 0 },
          { label: '6–8 weeks – manageable but with chasing and delays', value: 1 },
          { label: '3–5 weeks – reasonable but could be faster', value: 2 },
          { label: 'Under 3 weeks – or continuous performance replaces annual cycles', value: 4 },
        ],
      },
      {
        id: 'pm3', type: 'maturity', text: 'How are employee flight risks currently identified?',
        options: [
          { label: 'They aren\'t – resignations regularly come as a surprise', value: 0 },
          { label: 'Informally, through manager instinct and 1-to-1 conversations', value: 1 },
          { label: 'Exit interview trends reviewed retrospectively to spot patterns', value: 2 },
          { label: 'Predictive analytics flag at-risk employees 60–90 days in advance', value: 4 },
        ],
      },
      {
        id: 'pm4', type: 'maturity', text: 'How are individual goals connected to company strategy?',
        options: [
          { label: 'Goals set by managers independently – no formal cascade', value: 0 },
          { label: 'Company objectives are shared but team alignment is informal', value: 1 },
          { label: 'Structured goal-setting exists but cascade is manual and slow', value: 2 },
          { label: 'Company OKRs automatically cascade to team and individual goals', value: 4 },
        ],
      },
      {
        id: 'pm5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When a manager wants to address a performance issue formally, how long does the HR process typically take to initiate?',
        options: [
          { label: 'Weeks – HR capacity and process complexity create significant delays', value: 0 },
          { label: '1–2 weeks – HR is responsive but paperwork and approvals slow things', value: 1 },
          { label: 'A few days – a clear process exists and HR responds quickly', value: 2 },
          { label: 'Same day – self-service templates and HR advisory immediately available', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'er', num: '05', label: 'Employee Relations', color: '#F59E0B', impactWeight: 0.95, effortSaving: 'Up to 45%',
    questions: [
      {
        id: 'er1', type: 'maturity', text: 'What proportion of HR\'s time is spent answering routine employee queries?',
        options: [
          { label: 'More than half – it\'s the dominant activity for the HR team', value: 0 },
          { label: 'Around a third – significant but HR does other work too', value: 1 },
          { label: 'Less than a quarter – most queries handled through self-service', value: 2 },
          { label: 'Minimal – a chatbot handles the vast majority automatically', value: 4 },
        ],
      },
      {
        id: 'er2', type: 'maturity', text: 'How are formal ER cases (grievances, disciplinaries, absence) tracked and managed?',
        options: [
          { label: 'In email threads and personal files – no central tracking', value: 0 },
          { label: 'On a shared spreadsheet – inconsistent and hard to audit', value: 1 },
          { label: 'In an HR system but case notes are entered manually', value: 2 },
          { label: 'Case management system with workflows, AI-assisted notes, full audit trail', value: 4 },
        ],
      },
      {
        id: 'er3', type: 'maturity', text: 'How frequently is employee sentiment or engagement formally measured?',
        options: [
          { label: 'Once a year at most – an annual engagement survey', value: 0 },
          { label: 'Twice a year – results take weeks to analyse', value: 1 },
          { label: 'Quarterly pulse surveys – analysed manually by HR', value: 2 },
          { label: 'Continuous listening – real-time sentiment with AI-surfaced insights', value: 4 },
        ],
      },
      {
        id: 'er4', type: 'maturity', text: 'Are absence patterns analysed to identify wellbeing risks or management issues?',
        options: [
          { label: 'No – absence is recorded but never analysed for patterns', value: 0 },
          { label: 'HR reviews absence data occasionally when it becomes visible', value: 1 },
          { label: 'Absence triggers reviewed at team level during management reviews', value: 2 },
          { label: 'AI proactively flags patterns linked to team, manager, or role risk', value: 4 },
        ],
      },
      {
        id: 'er5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When an employee raises a concern or query, how long before they receive a substantive response from HR?',
        options: [
          { label: 'More than 3 days – HR is a known bottleneck for employee queries', value: 0 },
          { label: '1–3 days – reasonable but employees often chase', value: 1 },
          { label: 'Same day – HR is responsive and manages its inbox well', value: 2 },
          { label: 'Immediate – self-service or chatbot resolves most queries instantly', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'ops', num: '06', label: 'HR Operations', color: '#EF4444', impactWeight: 1.00, effortSaving: 'Up to 50%',
    questions: [
      {
        id: 'ops1', type: 'maturity', text: 'How do employees make routine HR requests?',
        options: [
          { label: 'By emailing or calling HR directly – each handled individually', value: 0 },
          { label: 'Via a form or shared inbox – logged but manually processed', value: 1 },
          { label: 'Through a self-service portal for some, not all, transactions', value: 2 },
          { label: 'Fully integrated self-service – HR only involved in exceptions', value: 4 },
        ],
      },
      {
        id: 'ops2', type: 'maturity', text: 'How is HR management reporting produced?',
        options: [
          { label: 'Manually compiled in Excel from multiple system exports each time', value: 0 },
          { label: 'Some reports automated, others still manual – inconsistent', value: 1 },
          { label: 'Most standard reports automated; analysis and commentary manual', value: 2 },
          { label: 'Automated dashboard with AI-generated insight summaries', value: 4 },
        ],
      },
      {
        id: 'ops3', type: 'maturity', text: 'How are changes to employment terms (pay, promotions, role changes) processed?',
        options: [
          { label: 'Via email approval chains and manual updates to multiple systems', value: 0 },
          { label: 'A paper or digital form submitted to HR, then manually updated', value: 1 },
          { label: 'An HR system workflow but some steps require manual intervention', value: 2 },
          { label: 'Fully automated – approved changes flow across all systems instantly', value: 4 },
        ],
      },
      {
        id: 'ops4', type: 'maturity', text: 'How would you describe the HR team\'s capacity split between admin and strategic work?',
        options: [
          { label: 'Predominantly admin – strategy is squeezed out by operational demand', value: 0 },
          { label: 'Roughly half and half – admin always wins when busy', value: 1 },
          { label: 'More strategic than admin – but admin burden still significant', value: 2 },
          { label: 'Primarily strategic – automation handles the operational load', value: 4 },
        ],
      },
      {
        id: 'ops5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When a line manager needs a standard HR document, how long does it typically take?',
        options: [
          { label: 'More than a week – HR has a backlog and documents queue up', value: 0 },
          { label: '3–5 days – HR processes it when capacity allows', value: 1 },
          { label: '1–2 days – HR turns it around reasonably quickly', value: 2 },
          { label: 'Same day or instant – generated automatically on request', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'pay', num: '07', label: 'Payroll & Compliance', color: '#EC4899', impactWeight: 0.80, effortSaving: 'Up to 40%',
    questions: [
      {
        id: 'pay1', type: 'maturity', text: 'How are payroll errors and exceptions identified before payroll runs?',
        options: [
          { label: 'They often aren\'t – errors are found after payroll has run', value: 0 },
          { label: 'Manual checking by the payroll team against a checklist', value: 1 },
          { label: 'System-generated exception reports reviewed manually each run', value: 2 },
          { label: 'AI flags anomalies automatically in advance – exceptions only reviewed', value: 4 },
        ],
      },
      {
        id: 'pay2', type: 'maturity', text: 'How is right-to-work, DBS, and professional certification compliance tracked?',
        options: [
          { label: 'On spreadsheets or paper files – renewals are often missed', value: 0 },
          { label: 'In the HRIS but expiry alerts are manual and frequently overlooked', value: 1 },
          { label: 'Automated alerts for expiry dates; chasing and storage still manual', value: 2 },
          { label: 'Fully automated – alerts, chasing, and secure storage system-managed', value: 4 },
        ],
      },
      {
        id: 'pay3', type: 'maturity', text: 'How is statutory HR reporting produced (Gender Pay Gap, ethnicity pay, diversity)?',
        options: [
          { label: 'Manually assembled by the HR team over several days each cycle', value: 0 },
          { label: 'Data pulled manually from systems then formatted for submission', value: 1 },
          { label: 'Partially automated data extraction; narrative and formatting manual', value: 2 },
          { label: 'Fully automated report generation with minimal HR intervention', value: 4 },
        ],
      },
      {
        id: 'pay4', type: 'maturity', text: 'Is there a complete, real-time audit trail for pay and compliance decisions?',
        options: [
          { label: 'No – records scattered across emails, files, and systems', value: 0 },
          { label: 'Partial – some changes logged but the trail is incomplete', value: 1 },
          { label: 'Most changes logged in the HRIS but not always in real time', value: 2 },
          { label: 'Full audit trail maintained automatically across all systems', value: 4 },
        ],
      },
      {
        id: 'pay5', type: 'bottleneck', text: 'BOTTLENECK CHECK – How many payroll corrections or pay queries does the team handle after each payroll run?',
        options: [
          { label: 'High volume – corrections and queries are a recurring post-payroll event', value: 0 },
          { label: 'Moderate – a handful of corrections expected each cycle', value: 1 },
          { label: 'Low – occasional errors only, resolved quickly', value: 2 },
          { label: 'Rare – pre-run AI validation catches issues before they reach employees', value: 4 },
        ],
      },
    ],
  },
  {
    id: 'pa', num: '08', label: 'People Analytics', color: '#14B8A6', impactWeight: 0.75, effortSaving: 'Up to 40%',
    questions: [
      {
        id: 'pa1', type: 'maturity', text: 'How are decisions about workforce planning, hiring, and restructuring made?',
        options: [
          { label: 'Manager instinct and budget availability – no data involved', value: 0 },
          { label: 'Informed by basic headcount reports; primarily judgment-led', value: 1 },
          { label: 'Informed by historical data and trends but not predictive modelling', value: 2 },
          { label: 'Supported by predictive analytics – scenarios modelled before deciding', value: 4 },
        ],
      },
      {
        id: 'pa2', type: 'maturity', text: 'Can HR currently identify which employees are most at risk of leaving in the next 90 days?',
        options: [
          { label: 'No – turnover is reactive; resignations regularly come as a surprise', value: 0 },
          { label: 'Managers flag concerns informally; no systematic process', value: 1 },
          { label: 'Exit interview trends reviewed retrospectively to spot patterns', value: 2 },
          { label: 'A predictive model actively identifies flight risks with time to act', value: 4 },
        ],
      },
      {
        id: 'pa3', type: 'maturity', text: 'How integrated is people data across systems (HRIS, payroll, L&D, engagement)?',
        options: [
          { label: 'Siloed – each system holds its own data with no joined-up view', value: 0 },
          { label: 'Data manually combined in Excel for reporting purposes', value: 1 },
          { label: 'Some integrations exist – partial view available but not real time', value: 2 },
          { label: 'Single integrated data layer giving a real-time unified view', value: 4 },
        ],
      },
      {
        id: 'pa4', type: 'maturity', text: 'Can HR quantify the financial impact of people decisions?',
        options: [
          { label: 'No – people decisions rarely connected to financial outcomes', value: 0 },
          { label: 'Rough estimates produced occasionally for business cases', value: 1 },
          { label: 'Some metrics tracked but not linked to outcomes', value: 2 },
          { label: 'HR regularly produces financial modelling for people investment decisions', value: 4 },
        ],
      },
      {
        id: 'pa5', type: 'bottleneck', text: 'BOTTLENECK CHECK – When the CEO asks HR for a people insight, how long does it take to produce?',
        options: [
          { label: 'Days or weeks – data has to be pulled and assembled manually', value: 0 },
          { label: 'A day – an analyst runs reports and compiles the answer', value: 1 },
          { label: 'A few hours – reports mostly automated but need formatting', value: 2 },
          { label: 'Instant – a live dashboard or AI query answers in real time', value: 4 },
        ],
      },
    ],
  },
];

export const DEPENDENCY_QS = [
  {
    id: 'dep1', text: 'Which HR process generates the most complaints or frustration from line managers?',
    options: [
      { label: 'Getting roles filled – hiring is slow and unreliable', area: 'ta' },
      { label: 'Getting HR documents and admin processed – too much waiting', area: 'ops' },
      { label: 'Managing performance and having HR support those conversations', area: 'pm' },
      { label: 'Getting answers to HR policies and employee queries', area: 'er' },
    ],
  },
  {
    id: 'dep2', text: 'Which HR failure most directly damages the business\'s ability to operate day-to-day?',
    options: [
      { label: 'Vacancies taking too long to fill – teams are understaffed', area: 'ta' },
      { label: 'New hires taking too long to become productive', area: 'ob' },
      { label: 'HR admin creating delays and errors in employment changes', area: 'ops' },
      { label: 'Payroll or compliance errors causing legal or ER risk', area: 'pay' },
    ],
  },
  {
    id: 'dep3', text: 'If you could fix only one HR process today, which would create the greatest business impact?',
    options: [
      { label: 'Faster, higher-quality hiring', area: 'ta' },
      { label: 'Better onboarding – reducing early attrition and time-to-productivity', area: 'ob' },
      { label: 'Reducing HR admin time to free capacity for strategic work', area: 'ops' },
      { label: 'Using people data to make better business decisions', area: 'pa' },
    ],
  },
  {
    id: 'dep4', text: 'Where does HR most often become a blocker rather than an enabler for the business?',
    options: [
      { label: 'Recruitment – too slow, too much HR involvement required', area: 'ta' },
      { label: 'Employee queries – HR response times frustrate employees and managers', area: 'er' },
      { label: 'People changes (promotions, role changes, leavers) – manual and slow', area: 'ops' },
      { label: 'Performance and development – managers don\'t use HR tools or processes', area: 'pm' },
    ],
  },
];

export const AI_SOLUTIONS = {
  ta: [
    {
      title: 'AI CV Screening & Intelligent Shortlisting',
      tag: 'Core Fix',
      impact: 'Very High',
      what: 'An LLM-powered screening layer sits on top of your ATS. Every application is parsed, scored against a structured role brief, and ranked. A shortlist of the top 10–15% is generated automatically – with a rationale for each candidate.',
      replaces: 'Manual recruiter CV review, keyword filtering, subjective first-pass decisions',
      saving: 'Up to 60% of recruiter time per role',
      roi: 'Typical saving: 2–4 hrs per role × volume = significant FTE reclaim',
      timeToValue: '4–8 weeks',
      complexity: 'Low',
      tools: ['Occupop', 'Ashby AI', 'Greenhouse + AI layer', 'Custom LLM on ATS export'],
    },
    {
      title: 'AI Job Description Generator & Bias Checker',
      tag: 'Quick Win',
      impact: 'High',
      what: 'Recruiters input role title, level, and 3–4 key requirements. AI drafts a complete, market-benchmarked JD in under 2 minutes – checking for gendered language, inclusion gaps, and salary competitiveness against live market data.',
      replaces: 'Manual JD writing from scratch or copy-paste from old versions, external copywriting costs',
      saving: '30% faster time-to-advertise per role',
      roi: 'Faster fills + better candidate quality from improved JD clarity',
      timeToValue: '1–2 weeks',
      complexity: 'Low',
      tools: ['Textio', 'Ongig', 'Custom GPT-4o prompt', 'Paradox'],
    },
    {
      title: 'Candidate Communication & Scheduling Bot',
      tag: 'Volume Multiplier',
      impact: 'High',
      what: 'A conversational AI handles 100% of candidate-facing communication: acknowledgements, status updates, interview scheduling (including calendar sync), rejection emails, and pre-screening Q&A. Recruiters only interact at interview and offer stage.',
      replaces: 'Manual recruiter email management, phone tag, scheduling back-and-forth, rejection drafting',
      saving: '3–5 FTE equivalent across a typical mid-market recruitment function',
      roi: 'Candidate NPS increases; recruiter capacity freed for strategic sourcing',
      timeToValue: '6–10 weeks',
      complexity: 'Medium',
      tools: ['Paradox (Olivia)', 'HireVue', 'Phenom', 'Custom chatbot on ATS webhooks'],
    },
  ],
  ob: [
    {
      title: 'AI Onboarding Chatbot & Digital Companion',
      tag: 'Core Fix',
      impact: 'Very High',
      what: 'A conversational AI guides every new hire through pre-boarding and the first 90 days – answering policy questions, completing compliance tasks, connecting to colleagues, and surfacing relevant content proactively. Available 24/7 with no HR involvement.',
      replaces: 'HR fielding first-30-day questions, inconsistent line manager onboarding, static intranet pages',
      saving: 'Up to 70% of onboarding HR effort; 20–30% reduction in 90-day attrition',
      roi: 'Replacing even 1 early leaver at 1× salary = ROI on entire implementation',
      timeToValue: '8–12 weeks',
      complexity: 'Medium',
      tools: ['ServiceNow HR', 'Leena AI', 'Enboarder', 'Custom on MS Teams / Slack'],
    },
    {
      title: 'Contract & Document Auto-Generation',
      tag: 'Quick Win',
      impact: 'High',
      what: 'Employment contracts, offer letters, variation letters, and compliance packs are generated automatically from HRIS data the moment an offer is accepted. e-Signature workflow triggered immediately. No HR draughting, no manual data entry, no version errors.',
      replaces: 'Manual contract drafting, Word template population, email distribution, chasing for signatures',
      saving: '2–3 FTE equivalent; near-zero error rate on employment documents',
      roi: 'Reduces legal risk from document errors; dramatically improves candidate experience',
      timeToValue: '4–8 weeks',
      complexity: 'Low',
      tools: ['DocuSign CLM', 'Juro', 'Ironclad', 'HRIS-native (Workday, BambooHR)'],
    },
    {
      title: 'Personalised 30/60/90 Day Journey Builder',
      tag: 'Retention Driver',
      impact: 'High',
      what: 'AI builds a bespoke onboarding journey for each new hire from their role profile, level, department, and identified skills gaps. Milestones, check-ins, learning content, and stakeholder introductions are sequenced automatically and tracked to completion.',
      replaces: "Generic 'same for everyone' onboarding, manager-dependent experience, paper checklists",
      saving: 'Measurable reduction in time-to-productivity (typically 20–35% faster)',
      roi: 'Productivity gain on every hire; line managers freed from onboarding coordination',
      timeToValue: '10–14 weeks',
      complexity: 'Medium',
      tools: ['Enboarder', 'Zavvy', 'Workleap Onboarding', 'Custom LMS integration'],
    },
  ],
  ld: [
    {
      title: 'AI Content Authoring & Rapid Course Generation',
      tag: 'Core Fix',
      impact: 'Very High',
      what: 'L&D teams input source material (documents, SME recordings, existing slides) and AI generates complete courses, quizzes, scenarios, and microlearning modules. Content that previously took 6–8 weeks to commission and build is ready in days.',
      replaces: 'External agency commissioning, manual SCORM authoring, long content development cycles',
      saving: 'Up to 55% of L&D content production cost and time',
      roi: 'Faster response to business needs; dramatically reduced external spend',
      timeToValue: '2–4 weeks',
      complexity: 'Low',
      tools: ['Synthesia', 'Articulate AI', 'iSpring', 'Coursebox', 'Custom GPT-4o pipeline'],
    },
    {
      title: 'AI-Powered Personalised Learning Paths',
      tag: 'Engagement Driver',
      impact: 'High',
      what: 'Rather than a static catalogue, every employee sees a dynamically personalised learning feed – driven by their role, current skills profile, performance signals, and career goals. AI recommends, sequences, and nudges. Managers can review and adjust.',
      replaces: 'Generic LMS catalogues, annual training plans, manager-dependent development conversations',
      saving: '40% improvement in voluntary learning completion; measurable skills gap closure',
      roi: 'Reduced external hiring cost as internal skills grow; improved retention',
      timeToValue: '8–12 weeks',
      complexity: 'Medium',
      tools: ['Degreed', 'EdCast', 'Cornerstone AI', '360Learning', 'LinkedIn Learning AI'],
    },
    {
      title: 'Live Skills Inventory & Gap Mapping',
      tag: 'Strategic Enabler',
      impact: 'High',
      what: 'A continuously updated skills taxonomy maps every employee\'s current capabilities against role requirements and future business needs. AI identifies skills gaps at individual, team, and organisational level – feeding directly into L&D prioritisation and workforce planning.',
      replaces: 'Annual skills surveys, manual gap analysis in spreadsheets, reactive training planning',
      saving: 'Real-time visibility replacing months of analysis; data-driven L&D investment',
      roi: 'Board-level insight into capability risk; measurable reduction in critical skills gaps',
      timeToValue: '12–16 weeks',
      complexity: 'High',
      tools: ['Gloat', 'Fuel50', 'Beamery', 'Workday Skills Cloud', 'Eightfold AI'],
    },
  ],
  pm: [
    {
      title: 'AI-Assisted Performance Review Writing',
      tag: 'Core Fix',
      impact: 'Very High',
      what: 'At review time, AI aggregates performance data – goal completion, peer feedback, project outcomes, absence, and development activity – and drafts a structured review narrative for each employee. Managers read, adjust, and approve. No blank page. No inconsistency.',
      replaces: 'Managers writing reviews from scratch with no data, inconsistent quality, hours of management time',
      saving: 'Up to 65% reduction in manager time on performance admin per cycle',
      roi: 'Fairer reviews; higher quality; freed manager time redirected to development conversations',
      timeToValue: '8–14 weeks',
      complexity: 'Medium',
      tools: ['Leapsome AI', 'Lattice AI', 'CultureAmp', 'Betterworks', 'Workday Peakon'],
    },
    {
      title: 'Flight Risk Prediction & Retention Intelligence',
      tag: 'Revenue Protector',
      impact: 'Very High',
      what: 'An ML model runs continuously across HRIS, performance, engagement, and absence data to identify employees with elevated flight risk – typically 60–90 days before resignation. HR and line managers receive alerts with suggested retention interventions.',
      replaces: 'Reactive response to resignations, exit interview data arriving too late to act',
      saving: 'Prevents 1.5–2× annual salary per retained employee',
      roi: 'In a 500-person organisation at 15% attrition, preventing 10% of exits = £500k–£2m+ saved',
      timeToValue: '12–20 weeks',
      complexity: 'High',
      tools: ['Workday Peakon', 'CultureAmp Predictive', 'Visier', 'Orgnostic', 'Custom ML model'],
    },
    {
      title: 'Continuous Performance Signal Engine',
      tag: 'Cycle Eliminator',
      impact: 'High',
      what: 'Replaces or supplements the annual review cycle with continuous lightweight check-ins, goal updates, and manager nudges. AI aggregates signals throughout the year so that when formal review time arrives, data is already collected and calibration is evidence-based.',
      replaces: 'Annual review panic, chasing managers for incomplete forms, point-in-time bias in assessments',
      saving: 'Review cycle compressed from 6–8 weeks to under 2 weeks',
      roi: 'Significant reduction in HR admin; higher manager and employee satisfaction',
      timeToValue: '6–10 weeks',
      complexity: 'Medium',
      tools: ['15Five', 'Lattice', 'Leapsome', 'Betterworks', 'Reflect AI'],
    },
  ],
  er: [
    {
      title: 'AI HR Policy Chatbot & Virtual Agent',
      tag: 'Volume Eliminator',
      impact: 'Very High',
      what: 'A conversational AI – deployed on Teams, Slack, or intranet – answers employee questions about leave, pay, policies, benefits, and HR processes in natural language, 24/7. Escalates only complex or sensitive queries to a human. Handles 70%+ of routine HR query volume.',
      replaces: 'HR inbox management, phone calls for routine queries, policy document hunting on the intranet',
      saving: 'Up to 45% of ER team effort; 24/7 availability with instant response',
      roi: 'HR team freed for complex casework and strategic activity; employee experience transformed',
      timeToValue: '6–10 weeks',
      complexity: 'Medium',
      tools: ['Leena AI', 'ServiceNow Virtual Agent', 'Moveworks', 'Microsoft Copilot for HR', 'Custom RAG chatbot'],
    },
    {
      title: 'ER Case Management & AI Case Notes',
      tag: 'Risk Reducer',
      impact: 'High',
      what: 'A structured case management system where AI transcribes and summarises meetings, drafts case notes, suggests process steps based on case type, and maintains a complete, auditable timeline. Advisors spend time on judgment – not administration.',
      replaces: 'Manual case notes in emails, spreadsheet-based case tracking, inconsistent process application',
      saving: '50% faster case resolution; audit-ready records with no additional effort',
      roi: 'Reduced legal exposure from poor documentation; consistent ER outcomes',
      timeToValue: '8–12 weeks',
      complexity: 'Medium',
      tools: ['Dovetail HR', 'ER Tracker', 'ServiceNow HR Case', 'Custom on SharePoint + AI'],
    },
    {
      title: 'Sentiment Analytics & Early Warning System',
      tag: 'Prevention Engine',
      impact: 'Medium',
      what: 'NLP analyses survey responses, pulse data, and (where permitted) communication patterns to surface morale trends, at-risk teams, and manager-specific signals before they become formal ER cases. HR gets a weekly insight dashboard, not a quarterly report.',
      replaces: 'Annual engagement surveys with 3-month analysis lag, reactive ER caseload',
      saving: 'Issues surface weeks earlier; significant reduction in formal grievance volume',
      roi: 'Preventing one employment tribunal claim typically saves £15k–£50k in direct costs',
      timeToValue: '10–16 weeks',
      complexity: 'Medium',
      tools: ['Workday Peakon', 'Medallia', 'CultureAmp', 'Glint', 'Qualtrics EmployeeXM'],
    },
  ],
  ops: [
    {
      title: 'AI-Powered HR Self-Service Portal',
      tag: 'Core Fix',
      impact: 'Very High',
      what: 'A unified self-service layer – accessible via desktop, mobile, or Teams – where employees and managers handle every routine transaction: personal detail changes, flexible working requests, reference letters, purchase orders, leavers, and more. AI guides users through each request and routes automatically for approval.',
      replaces: 'HR email inbox, manual request processing, phone calls for standard transactions',
      saving: 'Up to 50% of HR operational effort; measurable inbox reduction from day one',
      roi: 'HR team capacity freed for business partnering and strategic activity',
      timeToValue: '8–14 weeks',
      complexity: 'Medium',
      tools: ['ServiceNow HR', 'SAP SuccessFactors', 'Workday', 'BambooHR', 'HiBob'],
    },
    {
      title: 'Automated Contract & Letter Generation',
      tag: 'Quick Win',
      impact: 'High',
      what: 'Every employment document – contracts, variations, promotion letters, flexible working agreements, references – generated automatically from HRIS data in seconds. Correct, compliant, and sent for e-signature without HR touching a keyboard.',
      replaces: 'Manual document drafting, Word template errors, version control problems, email distribution',
      saving: '2–3 FTE equivalent; documents produced in seconds not days',
      roi: 'Eliminates document errors that create legal risk; dramatically faster turnaround',
      timeToValue: '4–8 weeks',
      complexity: 'Low',
      tools: ['Juro', 'DocuSign CLM', 'Workday document generation', 'Custom template + API'],
    },
    {
      title: 'Automated HR Reporting & Insight Dashboard',
      tag: 'Time Reclaimer',
      impact: 'Medium',
      what: 'All standard HR reports – headcount, turnover, absence, diversity, cost – generated automatically on schedule and presented in a live executive dashboard. AI adds narrative commentary and flags anomalies. No manual data assembly, no Excel gymnastics.',
      replaces: 'Monthly manual report compilation, spreadsheet data merging, analyst time on formatting',
      saving: '60% of HR reporting time; reports available in real time not monthly',
      roi: 'HR leadership time redirected from reporting to insight and action',
      timeToValue: '6–10 weeks',
      complexity: 'Low',
      tools: ['Power BI + AI narratives', 'Tableau + Einstein', 'Visier', 'ChartHop', 'Sage People Analytics'],
    },
  ],
  pay: [
    {
      title: 'Pre-Payroll AI Exception Detection',
      tag: 'Error Eliminator',
      impact: 'High',
      what: 'An AI validation layer runs against every payroll dataset before submission – flagging anomalies, duplicate payments, missing timesheets, unusual variances, and compliance gaps. Payroll team reviews only exceptions, not every record.',
      replaces: 'Manual payroll checking against checklists, post-run error corrections, employee queries about wrong pay',
      saving: 'Up to 40% of payroll processing time; near-elimination of post-run corrections',
      roi: 'One prevented error on a senior salary = cost of several months of tooling',
      timeToValue: '6–10 weeks',
      complexity: 'Medium',
      tools: ['MHR iTrent AI', 'Zellis', 'ADP SmartCompliance', 'Custom rules engine + LLM'],
    },
    {
      title: 'Automated Compliance Tracking & Document Management',
      tag: 'Risk Reducer',
      impact: 'High',
      what: 'Every compliance requirement – right to work, DBS, professional certifications, mandatory training – tracked automatically with expiry alerts triggered weeks in advance. Documents stored securely and retrievable instantly for audit. Renewals chased automatically.',
      replaces: 'Spreadsheet-based compliance tracking, manual renewal reminders, paper document filing',
      saving: '80% of compliance administration time; zero missed renewals',
      roi: 'Avoiding a single right-to-work breach saves far more than implementation cost',
      timeToValue: '6–8 weeks',
      complexity: 'Low',
      tools: ['Onspring', 'ComplyTrack', 'HRIS-native compliance modules', 'SharePoint + Power Automate'],
    },
    {
      title: 'Statutory Reporting Automation',
      tag: 'Compliance Accelerator',
      impact: 'Medium',
      what: 'Gender Pay Gap, ethnicity pay, workforce diversity, and other statutory reports assembled automatically from integrated data sources. Narrative sections drafted by AI from the numbers. Submission-ready in hours, not the days it currently takes.',
      replaces: 'Weeks of manual data assembly, analyst time on statutory reporting, compliance risk from errors',
      saving: 'Statutory reporting effort reduced from weeks to hours per cycle',
      roi: 'Risk reduction + significant senior HR and analyst time reclaimed annually',
      timeToValue: '8–12 weeks',
      complexity: 'Medium',
      tools: ['Karian and Box', 'Paydata', 'Built on Power BI + HRIS data', 'Custom LLM reporting pipeline'],
    },
  ],
  pa: [
    {
      title: 'Attrition Prediction & Flight Risk Intelligence',
      tag: 'Revenue Protector',
      impact: 'Very High',
      what: 'An ML model runs continuously across integrated people data – performance, engagement, absence, tenure, promotion history, pay equity, manager changes – to score every employee\'s flight risk. HR and managers receive actionable alerts with 60–90 days to intervene.',
      replaces: 'Surprise resignations, reactive exit interviews, gut-feel retention decisions',
      saving: 'Prevents 1.5–2× salary cost per retained employee',
      roi: 'In a 500-person business at 15% attrition, preventing 10% of exits = £500k–£2m annual saving',
      timeToValue: '14–20 weeks',
      complexity: 'High',
      tools: ['Visier', 'Orgnostic', 'Workday People Analytics', 'One Model', 'Custom ML on HRIS data'],
    },
    {
      title: 'Integrated People Data Platform',
      tag: 'Foundation Layer',
      impact: 'High',
      what: 'A unified data layer that connects HRIS, payroll, L&D, ATS, and engagement systems into a single real-time people data model. Eliminates manual data reconciliation. Every downstream AI solution in this list depends on this integration layer being in place.',
      replaces: 'Siloed systems, monthly manual data exports, inconsistent data definitions across teams',
      saving: 'Single source of truth; enables all other analytics and AI use cases',
      roi: 'Foundational – enables ROI across the entire AI transformation programme',
      timeToValue: '12–20 weeks',
      complexity: 'High',
      tools: ['Workday', 'Visier', 'ChartHop', 'Azure Data Factory + Power BI', 'Rippling'],
    },
    {
      title: 'Natural Language People Analytics',
      tag: 'Democratiser',
      impact: 'High',
      what: 'Line managers and executives query people data in plain English – \'Show me attrition by department this quarter vs last year\' or \'Which teams have the highest absence rate?\' – and get instant, accurate, visualised answers. No analyst required.',
      replaces: 'Waiting days for analyst-generated reports, monthly static dashboards, data requests to HR',
      saving: 'Up to 40% of people analytics effort; decision speed dramatically improved',
      roi: 'Better decisions made faster; HR team freed from reactive data requests',
      timeToValue: '10–16 weeks',
      complexity: 'Medium',
      tools: ['Visier Natural Language Query', 'Workday Illuminate', 'Microsoft Copilot for HR', 'Power BI Q&A'],
    },
  ],
};
